### ISSUE TITLE
CLOSE

### ISSUE THREAD

**Issue by githubmll** [githubmll/996.Publicity#10]

**Comment by strawberry2077** [comment]
0x74C6Fe51310f0E35f660Ce69A1DF5478C3313CA6

**Comment by Ericlqw** [comment]
0x29aD6e2BF08b80447d84B4b44fcC1C6B195d8933

**Comment by githubmll** [comment]
> 0x74C6Fe51310f0E35f660Ce69A1DF5478C3313CA6

已空投，请查收。

**Comment by githubmll** [comment]
> 0x29aD6e2BF08b80447d84B4b44fcC1C6B195d8933

地址不对空投失败，可能原因：非BSC（币安智能链）地址

**Comment by xc233** [comment]
0x880c7a31489c6C8bdd6f89270a7C8E1b67249F74

**Comment by lxsunbin** [comment]
0x303b94F157E237d57df7baBd73D8f210E2A54755

**Comment by gcnyin** [comment]
0x743Dd326db07eDC3E52201bAb8a251520953e3a5

**Comment by 0x9bb1** [comment]
0x7afe0070506873A5d68A5848cfCD6b5D4FA839FD

**Comment by yanglhan** [comment]
0x4B8971b1179D25f4B2bD6ed19c5c3173b7B79dc1

**Comment by takkiTang** [comment]
0x10C13219Fb117F09DCD92131e4cFB425233aFF24

**Comment by HugoZou** [comment]
0xd4F6c3C4167526d70b70FF384bEAFc02AD2d783e

**Comment by MarcelArthur** [comment]
0x803E185305EDD575dd850Ddc260B476032431AAf

**Comment by treatest** [comment]
0x39C8919f5FF69C4e7D67F3D6868800FEf33D3299

**Comment by qyp19911009** [comment]
0x16De6035266e65F1126B255882D6Cb4534890d8a

**Comment by pjpjq** [comment]
0x01d1EA63501Ff33322120Da63A350032d8bc5bA7

**Comment by githubmll** [comment]
----------###以上已全部空投###----------
空投查询链接 https://bscscan.com/token/0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de

**Comment by xu7068** [comment]
> _No description provided._

0xed0dc5319d3d7eb970ba7be270db4a54ccb04d3a

**Comment by porcobosso** [comment]
0x7Af8A0D9b3f9eBf3012ccc0DDb6E0eB572E533EC

**Comment by oangeor** [comment]
0x2a92C5dFCBa561a4B0102466476a287C2a3fe458

**Comment by ttz6** [comment]
0x0b6B7e496dBb3cf2146B0694707c95B25c7caB8d

**Comment by oldbirdsixflower** [comment]
0x9CA6793566776b42Bce6b8EEe19D8d879098095E

**Comment by alwayscc** [comment]
0x23B3AE1AAffb62dFDD01A9Aa9db4b36D711dB295

**Comment by qyp19911009** [comment]
0x16De6035266e65F1126B255882D6Cb4534890d8a

**Comment by qyp19911009** [comment]
0x16De6035266e65F1126B255882D6Cb4534890d8a

**Comment by mabelyong** [comment]
0x59e3EaE78630B164eB753153E97638c39Aa8AE60

**Comment by wth007tbs** [comment]
0x7c188391fE2b42746128557B75611894819A0275

**Comment by Penguinmont** [comment]
0x22b31Fb3f90444eBF32710420F502234b98405b7

**Comment by githubmll** [comment]
> 0x29aD6e2BF08b80447d84B4b44fcC1C6B195d8933

空投成功，请查收

**Comment by githubmll** [comment]
----------###.2 以上地址已全部空投 ###----------
空投查询链接 https://bscscan.com/token/0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de

**Comment by wohuainiande** [comment]
0xB4521Fb085b7C3dE74eCf110396671382b080187

**Comment by sunshine666** [comment]
0xB7b896A6B4E440DEF0EC7B0C4bB45a1Ab36485A8

**Comment by chenfar** [comment]
0x010eD33F769201F74D0Bc2aB32f3D5cdD8793204

**Comment by heropoo** [comment]
0x751600EA30380d45bde15dC1BD056091C419B8e7

**Comment by leo-web3** [comment]
0x18796AD54e7393F90ae64e9fFA1A2ba6C3999999

**Comment by weiqianliu** [comment]
0x961b18f7e01443f39dAce9E1085A9bE7681C0a01

**Comment by leafture** [comment]
0x057860C8ece0233053C0ABe276613d4519e26d8A

**Comment by caimengjun** [comment]
0xba452109d8286Ca60ED16409199cC84D279f9901

**Comment by caimengjun** [comment]
0x425996d5876eFfFDC2546B5B29c4BbC18e145646

**Comment by HugoEOF** [comment]
已星
0x08e362Ce73427956260ED7049646e78e5cd7c30D

**Comment by bhshi** [comment]
0xFEb6f049A88E0c2f262Ddc6BAF3cfed17175F068

**Comment by githubmll** [comment]
> 已星
> 0x08e362Ce73427956260ED7049646e78e5cd7c30D

已空投

**Comment by githubmll** [comment]
> 0xFEb6f049A88E0c2f262Ddc6BAF3cfed17175F068

已空投

**Comment by githubmll** [comment]
> 0xB4521Fb085b7C3dE74eCf110396671382b080187
已空投

**Comment by githubmll** [comment]
> 0x010eD33F769201F74D0Bc2aB32f3D5cdD8793204

已空投

**Comment by githubmll** [comment]
> 0xB7b896A6B4E440DEF0EC7B0C4bB45a1Ab36485A8

done

**Comment by msbily17** [comment]
0xf13011D5723A84acCAc055b07075E90f5d63C493

**Comment by githubmll** [comment]
> 0xba452109d8286Ca60ED16409199cC84D279f9901

done

**Comment by githubmll** [comment]
> 0x961b18f7e01443f39dAce9E1085A9bE7681C0a01

done

**Comment by disigma** [comment]
0x7Ad1Fb01A30f5aB0Dffb364Ca3A21E28D25a6b94

**Comment by wohuainiande** [comment]
> > 0xB4521Fb085b7C3dE74eCf110396671382b080187
> > 已空投
在哪可以看到，为什么这个地址没有收到

**Comment by githubmll** [comment]
> > > 0xB4521Fb085b7C3dE74eCf110396671382b080187
> > > 已空投
> > > 在哪可以看到，为什么这个地址没有收到

用合约地址把996币加进去就能看到了，链上数据如下：
![image](https://user-images.githubusercontent.com/17825339/118463254-257b0880-b732-11eb-92d2-7d4efb8a1c48.png)

**Comment by WddVictor** [comment]
0xA7bDf1C03EA27477DedAdACcDFE46142a68f3f64

**Comment by laowangfacai** [comment]
0xd34d64990A575a7CFDa0c73e9f0Ce8831cf89eDd

**Comment by ileosea** [comment]
0x4b53c9802AEABEc195838f5AE2344f18C451dE5b

**Comment by ghost** [comment]
0xc4658D25c33359a9415D02B262E18f0dA58D4072

**Comment by Naivev** [comment]
0x781fbc74C89fa7E50DbA3A1132aeF075E8556cb1

**Comment by 0-8-4** [comment]
0xCe34Bd9EAF5F62A379d7386471F30C1349B6B38f

**Comment by ryanflys** [comment]
0x40C4fd0e6246748ac06c03419e159C8274F00776

**Comment by LingyuYin** [comment]
0x2f41805BEc8b497eF377cAdbEa4AeF18aAF4D2b1

**Comment by msbily17** [comment]
好像没有收到 空投哈

**Comment by leafture** [comment]
都他妈的傻逼吗，各个都往我邮箱发，卧槽你们的吗，老子不是空投的，老子只留了个地址，艹，老子的空投也没有到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月25日(周二) 下午5:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [githubmll/996.Publicity] Token 996ICU 代币空投区 # 留下BSC地址即可 (#10)




 
好像没有收到 空投哈

**Comment by msbily17** [comment]
发错了 别tm唧唧歪歪的&nbsp; 嘴巴干净点 草


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "githubmll/996.Publicity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [githubmll/996.Publicity] Token 996ICU 代币空投区 # 留下BSC地址即可 (#10)





 都他妈的傻逼吗，各个都往我邮箱发，卧槽你们的吗，老子不是空投的，老子只留了个地址，艹，老子的空投也没有到 
  
  
  
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2021年5月25日(周二) 下午5:50 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [githubmll/996.Publicity] Token 996ICU 代币空投区 # 留下BSC地址即可 (#10) 
  
  
  
  
   
 好像没有收到 空投哈

**Comment by facai666** [comment]
> _没有提供说明。_

0x53Db72Bd635e8a041DC07437A6736CfcD7A6add0

**Comment by facai666** [comment]
0x53Db72Bd635e8a041DC07437A6736CfcD7A6add0

**Comment by guizi327832749** [comment]
0xc95C221BC1c44bf35670f535b6c192889a4ca774

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
