### ISSUE TITLE
hey,im coming

### ISSUE THREAD

**Issue by leftzzc** [githubmll/996.Publicity#11]
0x50CbfBE942898136C595C487120469f5f0ECfe7a

**Comment by githubmll** [comment]
> 0x50CbfBE942898136C595C487120469f5f0ECfe7a

done

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
