### ISSUE TITLE
sheng

### ISSUE THREAD

**Issue by lancerlau** [githubmll/996.Publicity#12]
0x8C37c61c937e3af8C0A5997e2313F7823f83352F

**Comment by githubmll** [comment]
> 0x8C37c61c937e3af8C0A5997e2313F7823f83352F

done

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
