### ISSUE TITLE
来啦！

### ISSUE THREAD

**Issue by Cabbage-Cat** [githubmll/996.Publicity#15]
0x5E61f24066Fe2c4D08A65407d1f14D7Ba689901D

**Comment by githubmll** [comment]
done

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
