### ISSUE TITLE
支持群主🌚

### ISSUE THREAD

**Issue by kingcos** [githubmll/996.Publicity#16]
0xE830b9D7F458bba0a540ED0846d17EF4Ef6d75C8

**Comment by githubmll** [comment]
done

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
