### ISSUE TITLE
领个币

### ISSUE THREAD

**Issue by ZhangJoker** [githubmll/996.Publicity#18]
地址:
0x6fed8dd50BC8cA890D0D5b8693fA23ca2107ee70

**Comment by githubmll** [comment]
> 地址:
> 0x6fed8dd50BC8cA890D0D5b8693fA23ca2107ee70

done

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
