### ISSUE TITLE
现状

### ISSUE THREAD

**Issue by XuZhongCN** [githubmll/996.Publicity#2]
现在的问题应该不是影响力小，影响力已经足够，现在问题是，一个依法办事的问题，能否会因为法律规定如此，不惜GDP也要执行的问题。

**Comment by githubmll** [comment]
GitHub影响力不小了，但是在国内只是在IT行业很火，其它行业估计还都不知道 有996.ICU这么个事..,在国内影响力还不够。。

**Comment by XuZhongCN** [comment]
所以如果想要把996icu运动的影响力扩大到其他行业，似乎不是GitHub能搬到的事情了。
我在想，既然996icu上黑名单的企业已经那么多且证据确凿，为什么公检法不执法，这种情况下，起诉执法机关渎职是否可以，并不期望渎职罪名成立，只是期望通过这样的起诉，再次把996问题作为社会的关注点。

**Comment by githubmll** [comment]
嗯嗯，国家不出面的原因还是影响不够大... ,以为只是小大小闹
