### ISSUE TITLE
我也来啦

### ISSUE THREAD

**Issue by heropoo** [githubmll/996.Publicity#20]
0x751600EA30380d45bde15dC1BD056091C419B8e7

**Comment by githubmll** [comment]
> 0x751600EA30380d45bde15dC1BD056091C419B8e7

done

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
