### ISSUE TITLE
9107's worker.

### ISSUE THREAD

**Issue by lovemylovelygirl** [githubmll/996.Publicity#23]
0x848c49fD3FE4dD05831703a5E5934446d9CaD60F

**Comment by githubmll** [comment]
> 0x848c49fD3FE4dD05831703a5E5934446d9CaD60F

done

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
