### ISSUE TITLE
My BSC address

### ISSUE THREAD

**Issue by shansongliu** [githubmll/996.Publicity#24]
0xD9f2F1DB01F747cF698a17594aAc0B731Cfd6210

**Comment by githubmll** [comment]
> 0xD9f2F1DB01F747cF698a17594aAc0B731Cfd6210

已空投

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
