### ISSUE TITLE
空投

### ISSUE THREAD

**Issue by liupeng110** [githubmll/996.Publicity#25]
0xAc0FaE1379D4469349e14e29e12092A9A987E27C

**Comment by githubmll** [comment]
> 0xAc0FaE1379D4469349e14e29e12092A9A987E27C
> 老歌问下，p-i-g 这个代码一直remix上部署不起来，能不能看下https://github.com/pigtokenfinance/contracts

done

**Comment by WddVictor** [comment]
0xA7bDf1C03EA27477DedAdACcDFE46142a68f3f64

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
