### ISSUE TITLE
兄弟你是怎么在996.ICU上开新的Pull Request的？

### ISSUE THREAD

**Issue by posclegom** [githubmll/996.Publicity#27]
我试图在996.ICU上开新的Pull Request，结果刚刚摁下merge按钮，就被account suspended了。连续砸了两个小号。

多谢帮助。

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换
