### ISSUE TITLE
关于现有平台的咨询

### ISSUE THREAD

**Issue by CPdogson** [githubmll/996.Publicity#3]
除了微信公众号以外，是否注册了别的平台，比较重要的有
头条号
百家号
知乎文章
微博
以及论坛和百度贴吧

如有有余力的话可以尝试经营，我的文章也会发给你进行传播

**Comment by githubmll** [comment]
> 除了微信公众号以外，是否注册了别的平台，比较重要的有
> 头条号
> 百家号
> 知乎文章
> 微博
> 以及论坛和百度贴吧
> 
> 如有有余力的话可以尝试经营，我的文章也会发给你进行传播

这些有是有，不过没那么多的时间
