### ISSUE TITLE
求空投 随便问一下这么加群 

### ISSUE THREAD

**Issue by msbily17** [githubmll/996.Publicity#31]
0xf13011D5723A84acCAc055b07075E90f5d63C493    我实在电报认识的 求入群

**Comment by githubmll** [comment]
空投已结束，愉快的兑换吧
浏览器兑换方式(MetaMask或其它插件钱包)操作方式：
https://bsc.mdex.com/#/swap?inputCurrency=0xbc61ddf92f9d5ebe8c0d1a52dbd38529f67a79de
手机APP TokenPocket(TP)操作方式：发现-DApps-Mdex(bsc)- BNB/996 即可兑换

**Comment by githubmll** [comment]
Telegram
https://t.me/joinchat/H5VWoLIAkqdhNzdl
