### ISSUE TITLE
信息公开：996icu爆发一个月，我很关心劳动监察部门

### ISSUE THREAD

**Issue by CPdogson** [githubmll/996.Publicity#8]
https://github.com/CPdogson/996action/blob/master/Press-releases/Gov-info.md

https://github.com/CPdogson/996action/blob/master/Press-releases/%E4%BF%A1%E6%81%AF%E5%85%AC%E5%BC%80%EF%BC%9A996icu%E7%88%86%E5%8F%91%E4%B8%80%E4%B8%AA%E6%9C%88%EF%BC%8C%E6%88%91%E5%BE%88%E5%85%B3%E5%BF%83%E5%8A%B3%E5%8A%A8%E7%9B%91%E5%AF%9F%E9%83%A8%E9%97%A8.docx

欢迎大家转载传阅

**Comment by githubmll** [comment]
OK ，感谢分享，今天转发一下

**Comment by CPdogson** [comment]
你的那个群有别的人寄了吗？把线索发给我或者在我的issues上发一下？

**Comment by githubmll** [comment]
> 你的那个群有别的人寄了吗？把线索发给我或者在我的issues上发一下？

目前正在收集中

**Comment by CPdogson** [comment]
> 
> 
> > 你的那个群有别的人寄了吗？把线索发给我或者在我的issues上发一下？
> 
> 目前正在收集中

下面还有篇寄送劳动法的稿子，你也可以发下
